eureka:
  client:
    enabled: false

server:
  port: ${PORT:8086}

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true
management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

app:
  cors:
    allowed-origins: http://localhost:3000

spring:
  application:
    name: users-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8082/realms/digital-media
            jwk-set-uri: http://localhost:8082/realms/digital-media/protocol/openid-connect/certs
        registration:
          keycloak:
            client-id: microservicios
            client-secret: h1lZxa6kKaojbaq10TfCP7CoTL5xvf3Q
            scope: openid
            redirect_uri: http://localhost:8080


  data:
    mongodb:
      host: localhost
      port: 27015
      password: root
      username: root
      authentication-database: root
      database: db-users-2


  main:
    allow-circular-references: true
