spring:
  application:
    name: ms-bill
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/digital-media
            jwk-set-uri: http://localhost:8080/realms/digital-media/protocol/openid-connect/certs
        registration:
          keycloak:
            client-id: microservicios
            client-secret: h1lZxa6kKaojbaq10TfCP7CoTL5xvf3Q
            scope: openid
            redirect_uri: http://localhost:8088/login/oauth2/code/keycloak
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${PORT:8088}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true