server:
  port: ${PORT:8080}


spring:
  application:
    name: dh-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: users-service
          uri: http://localhost:8086
          predicates:
            - Path=/users/**

        - id: movies-service
          uri: http://localhost:8085
          predicates:
            - Path=/movies/**

        - id: ms-bill
          uri: http://localhost:8088
          predicates:
            - Path=/bills/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://localhost:8082/realms/digital-media
            token-uri: http://localhost:8082/realms/digital-media/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: microservicios
            client-secret: h1lZxa6kKaojbaq10TfCP7CoTL5xvf3Q
            scope: openid
            redirect_uri: http://localhost:8080//login/oauth2/code/keycloak


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka