spring:
  application:
    name: movies-service
  spring:
    application:
      name: ms-bill
    security:
      oauth2:
        client:
          provider:
            keycloak:
              issuer-uri: http://localhost:8082/realms/digital-media
              jwk-set-uri: http://localhost:8082/realms/digital-media/protocol/openid-connect/certs
          registration:
            keycloak:
              client-id: microservicios
              client-secret: h1lZxa6kKaojbaq10TfCP7CoTL5xvf3Q
              scope: openid
              redirect_uri: http://localhost:8080

  data:
    mongodb:
      host: localhost
      port: 27016
      password: root
      username: root
      authentication-database: root
      database: db-movies-2

app:
  cors:
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true
server:
  port: ${PORT:8085}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

